import "./EventCard.css";
// import cardImage from "../../../assets/card-image.jpg";

export default function EventCard({
  event_id,
  image,
  title,
  date,
  distance,
  commute,
  tag1,
  tag2,
  start_time,
  end_time,
  time_total,
  time_motion,
  avg_speed,
  avg_motion_speed,
  uphill,
  downhill,
  altitude_min,
  altitude_max,
}) {
  return (
    <li className="card-details">
      <div className="card-image">
        <img src={image} alt="Event album cover" />
      </div>
      <div className="card-date">Date: {date}</div>
      <div className="card-distance">Distance: {distance}</div>
      <div className="card-title">{title}</div>
      <div className="card-tags">
        <span className="card-tags__event-type">{tag1}</span> 
        <span className="card-tags__duration">{tag2}</span>
        <span className="card-tags__event-id">{event_id}</span>
      </div>
      <ul className="card-stat1">
        <li>Start Time: {start_time}</li>
        <li>End Time: {end_time}</li>
        <li>Time Total: {time_total}</li>
        <li>Time Motion: {time_motion}</li>
      </ul>
      <ul className="card-stat2">
        <li>Avg Speed (stops included): {avg_speed}</li>
        <li>Avg Motion Speed: {avg_motion_speed}</li>
        <li>Uphill: {uphill}</li>
        <li>Downhill: {downhill}</li>
        <li>Altitude Range: {altitude_min} - {altitude_max}</li>
      </ul>    
    </li>
  );
}

// export default function EventCard() {
//   return (
//     <div className="card-details">
//       <div className="card-image">
//         <img src={cardImage} alt="Event album cover" />
//       </div>
//       <div className="card-date">Date: 2023-09-16</div>
//       <div className="card-distance">Distance: 82 km</div>
//       <div className="card-title">Rouge National Urban Park</div>
//       <div className="card-tags">
//         <span className="card-tags__event-type">Cycling</span> 
//         <span className="card-tags__duration">One-Day</span>
//         <span className="card-tags__event-id">v2310</span>
//       </div>
//       <ul className="card-stat1">
//         <li>Start Time: 9:47</li>
//         <li>End Time: 18:46</li>
//         <li>Time Total: 8:59</li>
//         <li>Time Motion: 5:50</li>
//       </ul>
//       <ul className="card-stat2">
//         <li>Avg Speed (stops included): 9.1</li>
//         <li>Avg Motion Speed: 13.9</li>
//         <li>Uphill: 454 m</li>
//         <li>Downhill: 637 m</li>
//         <li>Altitude Range: 43 - 349</li>
//       </ul>      
//     </div>
//   );
// }


  /* <div class="card-details">
    <div class="card-header">Rouge National Urban Park</div>
    <div><span>Date:</span> <span>2023-09-16</span></div>
    <div><span>Distance:</span> <span>82 km (+ 16 km commute)</span></div>
    <div><span>Cycling</span> <span>One-Day</span></div>
    <div><span>Start Time:</span> <span>9:47</span></div>
    <div><span>End Time:</span> <span>18:46</span></div>
    <div><span>Time Total:</span> <span>8:59</span></div>
    <div><span>Time Motion:</span> <span>5:50</span></div>
    <div><span>Avg Speed (stops included):</span> <span>9.1</span></div>
    <div><span>Avg Motion Speed:</span> <span>13.9</span></div>
    <div><span>Uphill:</span> <span>454 m</span></div>
    <div><span>Downhill:</span> <span>637 m</span></div>
    <div><span>Altitude Range:</span> <span>43 - 349</span></div>
    <div class="card-footer">
      <span>Generated by YourActivityTracker.com</span>
    </div>
  </div> */

